ControleEstoque/ControleEstoqueAplication/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ControleEstoqueAplication.Models
{
    public class LoginViewModel
    {
        //Atributos NAME->Escrito o formulario USUARIO, incluiu os atributos nome,senha e lembrar me, utilizando o
        [Required(ErrorMessage ="Informe seu usuário")]
        [Display(Name ="Usuário: ")]
        public string Usuario { get; set; }

        [Required(ErrorMessage = "Informe sua Senha")]
        [DataType(DataType.Password)]
        [Display(Name = "Senha: ")]
        public string Senha { get; set; }

        [Display(Name = "Lembrar Me")]
        public bool LembrarMe { get; set; }
    }
}

ControleEstoque/ControleEstoqueAplication/Controllers/ContaUsuarioController.cs
using ControleEstoqueAplication.Models;
using System.Web.Mvc;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

//colocando no banco de dados 

namespace ControleEstoqueAplication.Controllers
{
    public class ContaUsuarioController : Controller
    {
        //esta passando o allownanonymous para todo mundo acessar 
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            //Quando logar, vai voltar para a URL PRIVADA AO SE LOGAR
            ViewBag.ReturnUrl = returnUrl;
            return View();

        }
        [HttpPost]
        [AllowAnonymous]
        
        //criando o methodo POST possuindo 2 parametros -> Login e a URL de retorno ao logar
        public ActionResult Login(LoginViewModel login, string returnUrl)
        {
            //Validando o login do usuario, se tiver invalido, vai retornar a tela de LOGIN, se estiver correto, vai retornar o menu todo Authorized
            if (!ModelState.IsValid)
            {
                return View(login);
            }
            var achou = UsuarioModel.ValidarUsuario(login.Usuario, login.Senha);

            if (achou)
            {
                FormsAuthentication.SetAuthCookie(login.Usuario, login.LembrarMe);
                if (Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                else
                {
                    RedirectToAction("Index", "Home");
                }
            }
            else
            // se n achar o login
            {
                ModelState.AddModelError("", "Login Invalido.");
            }
            return View(login);
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
           return RedirectToAction("Index","Home");

        }

    }
}

ControleEstoque/ControleEstoqueAplication/Views/ContaUsuario/Login.cshtml
@model ControleEstoqueAplication.Models.LoginViewModel
@{

    ViewBag.Title = "Login";
}

<div class="container" id="cContainer">
    <div class="row">
        <h3 class="titulo navbar">Auto Peças - Zaquel</h3>
        <h2 class="display-4">Login de usuário</h2>
    </div>
    <div class="row">
        <section id="loginform">
            
            @using (Html.BeginForm("Login", "ContaUsuario", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Usuario, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        
                        @Html.TextBoxFor(m => m.Usuario, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Usuario, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Senha, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Senha, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Senha, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2">
                        @Html.CheckBoxFor(m => m.LembrarMe)
                        @Html.LabelFor(m => m.LembrarMe)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2">
                        <input type="submit" class="btn btn-success" value="Entrar" />
                    </div>
                </div>

            }
        </section>
    </div>
</div>


@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}