ControleEstoque/ControleEstoqueAplication/Controllers/CadastroController.cs
using ControleEstoqueAplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoqueAplication.Controllers
{
    //autorizo quando o login for bem sucedido 
    public class CadastroController : Controller
    {
        private static List<GrupoProdutoModel> _listaGrupoProduto = new List<GrupoProdutoModel>()
        {
            new GrupoProdutoModel(){Id=1,Nome="Livros",Ativo=true},
            new GrupoProdutoModel(){Id=2,Nome="Mouses",Ativo=true},
            new GrupoProdutoModel(){Id=3,Nome="Monitores",Ativo=false}
        };

        [Authorize]
        public ActionResult GrupoProduto()
        {
            return View(_listaGrupoProduto);
        }
        [Authorize]
        public ActionResult MarcaProduto()
        {
            return View();
        }
        [Authorize]
        public ActionResult LocalProduto()
        {
            return View();
        }
        [Authorize]
        public ActionResult UnidadeMedida()
        {
            return View();
        }
        [Authorize]
        public ActionResult Produto()
        {
            return View();
        }
        [Authorize]
        public ActionResult Pais()
        {
            return View();
        }
        [Authorize]
        public ActionResult Estado()
        {
            return View();
        }
        [Authorize]
        public ActionResult Cidade()
        {
            return View();
        }
        [Authorize]
        public ActionResult Fornecedore()
        {
            return View();
        }
        [Authorize]
        public ActionResult PerfilUsuario()
        {
            return View();
        }
        [Authorize]
        public ActionResult Usuario()
        {
            return View();
        }
    }
}

ControleEstoque/ControleEstoqueAplication/Controllers/GraficoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoqueAplication.Controllers
{
    public class GraficoController : Controller
    {
        [Authorize]

        public ActionResult Perdas()
        {
            return View();
        }
        [Authorize]
        public ActionResult EntradasSaidaMes()
        {
            return View();
        }
    }
}

ControleEstoque/ControleEstoqueAplication/Controllers/OperacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoqueAplication.Controllers
{
    public class OperacaoController : Controller
    {
        [Authorize]
        public ActionResult EntradaEstoque()
        {
            return View();
        }
        [Authorize]
        public ActionResult SaidaEstoque()
        {
            return View();
        }
        [Authorize]
        public ActionResult LancPerdaProduto()
        {
            return View();
        }
        [Authorize]
        public ActionResult Inventario()
        {
            return View();
        }
    }
}

ControleEstoque/ControleEstoqueAplication/Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoqueAplication.Controllers
{
    public class RelatorioController : Controller
    {
        [Authorize]
        public ActionResult PosicaoEstoque()
        {
            return View();
        }
        [Authorize]
        public ActionResult Pcompras()
        {
            return View();
        }
    }
}

ControleEstoque/ControleEstoqueAplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Controle de Estoque</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Controle de Estoque", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Cadastro
                                <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Produtos", "Produto", "Cadastro")</li>
                                <li>@Html.ActionLink("Grupo de produtos", "GrupoProduto", "Cadastro")</li>
                                <li>@Html.ActionLink("Marcas de Produtos", "MarcaProduto", "Cadastro")</li>
                                <li>@Html.ActionLink("Locais de Armazenamento", "LocalProduto", "Cadastro")</li>
                                <li>@Html.ActionLink("Unidades de medidas", "UnidadeMedida", "Cadastro")</li>
                                <li class="nav-divider"></li>
                                <li>@Html.ActionLink("Países", "Pais", "Cadastro")</li>
                                <li>@Html.ActionLink("Estados", "Estado", "Cadastro")</li>
                                <li>@Html.ActionLink("Cidades", "Cidade", "Cadastro")</li>
                                <li>@Html.ActionLink("Fornecedores", "Fornecedore", "Cadastro")</li>
                                <li class="nav-divider"></li>
                                <li>@Html.ActionLink("Usuários", "Usuario", "Cadastro")</li>
                                <li>@Html.ActionLink("Perfis de Usuários", "PerfilUsuario", "Cadastro")</li>

                            </ul>
                        </li>

                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Operações
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Entrada de produtos", "EntradaEstoque", "Operacao")</li>
                                <li>@Html.ActionLink("Saidas de produtos", "SaidaEstoque", "Operacao")</li>
                                <li>@Html.ActionLink("Lançamentos de produtos", "LancPerdaProduto", "Operacao")</li>
                                <li>@Html.ActionLink("Inventário de estoque", "Inventario", "Operacao")</li>
                            </ul>
                        </li>

                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Relatórios
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Posição de Estoque", "PosicaoEstoque", "Relatorio")</li>
                                <li>@Html.ActionLink("Pedido de Compras", "Pcompras", "Relatorio")</li>
                            </ul>
                        </li>

                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Gráficos
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Perdas por mês", "Perdas", "Grafico")</li>
                                <li>@Html.ActionLink("Entradas e Saídas por mês", "EntradasSaidaMes", "Grafico")</li>
                            </ul>
                        </li>
                    </ul>

                    using (Html.BeginForm("LogOff", "ContaUsuario", FormMethod.Post, new { id = "logoffForm" }))
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>
                            <li><a href="#">Bem-Vindo(a): @User.Identity.Name</a></li>



                            <li><a href="javascript:document.getElementById('logoffForm').submit()">Sair</a></li>


                        </ul>
                    }
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Login", "Login", "ContaUsuario")</li>
                    </ul>
                }
            </div>

        </div>

    </div>

    <div class="container body-content">
        @RenderBody()

        <footer class="fixarRodape">
            <hr />
            <p>&copy; @DateTime.Now.Year - Controle de estoque</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>